### ISSUE TITLE
Should we do tabs?

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/DSCI-532_2024_2_pollution-tracker#115]
Discuss here!

**Comment by killerninja8** [comment]
I don't think tabs would add much value because our plots are closely related, and having all of them visible at once is quite beneficial. What do y'all think?

**Comment by meretelutz** [comment]
We agree! We really like the current layout and don't think tabs would add to it.

**Comment by killerninja8** [comment]
Awesome!
