### ISSUE TITLE
App Refinement

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/DSCI-532_2024_2_pollution-tracker#124]
This weeks it is time to tie it all together and deliver a production ready app. This section's grading will be more focused on the final stage of your app including smaller details that we have been softer on previously, like a well-styled, and nicely laid out app (fully functional is still the most important). Your final app will be evaluated on how it incorporates the best practices from lectures (unless you explained why you have deviated from them in the reflection).

Now you are allowed to get hung up of minor styling details, since you will be graded on this in milestone 4. However, please note that it does not need to be pixel perfect, especially not in a more advanced layout. We will not be zooming in on your app and check the smallest alignment problems, but if something is clearly not aligned in a full screen window or there is a lack of overall styling to the app, then that's issue.

**Comment by weiranzhao97** [comment]
- The current layout is considered explicit and logical, effectively supporting user navigation and data interpretation.
- Regarding the AQI color coding, although there is no official standardized version, maintaining the current palette is advisable. The use of dark red to denote severe pollution levels effectively highlights critical areas, aiding in immediate visual assessment.
