### ISSUE TITLE
Assess whether it is necessary to have the Altair/Plotly toolbars that show up on hover. If not, remove them (especially if you have many charts). A good reason for keeping them would be if it is important to e.g. download the charts.

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/DSCI-532_2024_2_pollution-tracker#128]

**Comment by killerninja8** [comment]
I think we should keep it since this dashboard is likely to be used by public health professionals, and they may need these plots to justify their decisions within reports and presentations. Up to y'all though, since it should be a quick change if we remove this functionality.

**Comment by meretelutz** [comment]
I think keeping this is a good idea! I especially appreciate having the 'reset axis' button pop up, as I frequently zoom in too far when scrolling down the dashboard. I also like the idea of our target audience being able to download the images. In the future we might consider adding this functionality for some of our other plots as well.
