### ISSUE TITLE
App design & functionality

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/DSCI-532_2024_2_pollution-tracker#33]
In this section you will implement most of the dashboard you outlined in
your proposal. but not every single detail. It's OK if you need to
deviate a bit from the proposal during implementation, but make sure to
write about it in the reflection section below. Any changes you make
should be compatible with your usage scenario and target audience. For
this milestone, you can follow the app complexity criteria mentioned
below; for later milestone the teaching team might give you feedback on
how to adjust the overall complexity of your final app (if needed).

-   For this milestone, your app should have a minimum of six input +
    output components in total (e.g. 2 inputs (widgets) + 4 outputs
    (charts, tables, text, etc.)), with a minimum of two of each (so you
    can't have 0 inputs and 6 outputs).
    -   Each of these six components should be linked to at least one
        callback.
    -   Talk to me if you were planning to use less than six components
        in your final app and we can discuss what you could add /
        modify.
-   All the elements of your dashboards should be laid out in grid
    format using rows and columns, while following the best practices we
    have talked about during lectures.
    -   E.g. the individual components should be assigned to variable
        names, that are then used in the layout.
-   Your interface should be as self-documenting as possible, with
    appropriate labels for panes and widgets, and an overall title for
    the dashboard.
-   Note that TAs will be grading your deployed app in a full-screen
    window. You don't need to worry about how it looks on a phone/narrow
    window.
-   At the bottom of the page, include a short description of the app,
    who has made it, a link to the repo, and the date of the latest
    update/deployment.
-   When selecting and implementing visualization, you are expected to
    follow the best practices taught in 531, or clearly explain in your
    proposal why you chose to deviate from them.

It can be easy to get sucked into a rabbit hole when trying to implement
a stubborn feature (I know this all too well myself =p). While it is
important to build your troubleshooting skills, it is often even more
important to build your time management skills and we do not want one
annoying bug to prevent you from completing your app. This is a short
project, so compromises may need to be made: if you get stuck on a
smaller feature, file an issue and move on.

**Comment by killerninja8** [comment]
We have to make a line chart (values over time), geographic plot (AQI values in different places), bar chart (ranked?), and ___

**Comment by carinaya** [comment]
Thanks @meretelutz for creating this issue and @killerninja8 for summarizing the work!

**Comment by meretelutz** [comment]
Requirements met! Good work team!
