### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/DSCI-532_2024_2_pollution-tracker#35]
Expand on the README file to be a welcoming place for anyone coming to
your project for the first time. For your project, your README should
cater to at least two groups of people:

1.  Those interested in using your dashboard
    -   Include motivation behind your project and clearly explain what
        problem you are solving and why it is important.
    -   You do not have to include detailed usage instructions, just
        high level what they can do in your dashboard and the deployed
        link.
    -   [This is a good
        example](https://github.com/KirstieJane/STEMMRoleModels)
    -   Include a link to your demo GIF in the README. It's sparks
        interest to see a demo of the app right away.
    -   Include a note on how to get support (e.g. opening an issue).
2.  Those interesting in running the app locally, and potentially
    helping you develop your dashboard
    -   Potential contributors are interested in the above as well, but
        also need to know how they can install your app/dependencies and
        how to run it locally.
    -   Include a link to the contributing file, where they can find out
        more if they are interested in making contributions to the repo.

**Comment by killerninja8** [comment]
Thanks for creating the issues, @meretelutz!
