### ISSUE TITLE
Data Wrangling and Feature Engineering

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/DSCI-532_2024_2_pollution-tracker#36]
Enact the feature engineering discussed in the project proposal:
* [Air Quality Index (AQI)](https://www.airnow.gov/aqi/aqi-basics/) for each pollutant 
* overall air quality score (TBD how to calculate this)

**Comment by killerninja8** [comment]
Dear Team,

Following our extensive and meticulous search, which included the review of numerous academic papers, we have discovered of a comprehensive Air Quality Index (AQI) calculator formula. This tool is accessible via the following links:

https://metone.com/how-to-calculate-aqi-and-nowcast-indices/, 
https://github.com/ThangLeQuoc/aqi-calculator

Cheers!

**Comment by meretelutz** [comment]
Great finds! That calculator looks especially useful. I'll be sure to use these resources in my feature engineering work.

**Comment by killerninja8** [comment]
Awesome!

**Comment by meretelutz** [comment]
Hi team! I was trying to get an [AQI package](https://pypi.org/project/python-aqi/) to work but it was giving me so many issues that I think we'll have to make our own calculations using a formula. This process will be super time intensive, so I think this might be a next week problem.

**Comment by meretelutz** [comment]
Came across some issues with the pollutant data, in that not all measurements of the pollutants have the same data. Looking into ways to convert everything to mg/m3, which seems to be the more popular unit of measurement

**Comment by meretelutz** [comment]
Hi guys @killerninja8 @carinaya @weiranzhao97 wanted to give y'all a quick update on all the wrangling! 

I standardized all the measurements into the right units for AQI calculations. Thanks to Sid who figured out the best way to convert our measurements into the AQI values.  The csv saved into our processed data folder should now be good to go for analysis! I think I incorporated all the pre-processing you guys had done individually, but if I missed anything, please let me know. Now 

Now that we have this processed file, we need to go back to the dashboard code and adjust it so that we now just load in the processed csv and are not doing the wrangling in the app.py file. 

One small issue is that we still have a considerable number of observations with NaN for AQI. I think this might be due to rounding errors from the formula to calculate AQI, as the measurements that are resulting in NaNs are either extremely small or outside the boundaries of AQI. We can talk about this the next time we have an in-person meeting, but for now I don't think we should be wasting any more time on this matter. And if worst comes to worse we can just use the measurements we have, rather than AQI scores.
