### ISSUE TITLE
Feedback from Wenwei (Joey) Wu

### ISSUE THREAD

**Issue by joeywwwu** [UBC-MDS/DSCI-532_2024_2_pollution-tracker#91]
# Peer Review for the Pollution Tracker Dashboard 
- Wenwei Wu @joeywwwu

## README Documentation 

- The README could be more explicit about how each element of the dashboard serves the user's goals. This would make the dashboard's capabilities clearer to new users.

## General Points

- Increase the font size for the "Worldwide Comparison" and "Country of Interest Trend" section titles for better visibility.
- Perhaps consider introducing tabs for different pollutants to better subdivide these selections for better artistic effects.
- Would be better if there was a theme color tone for the entire dashboard. For example, could use green or brown as the theme color as the dashboard is about pollutants and the environment. 

## Worldwide Distribution Map

- The world distribution map could be improved by adding interactive elements such as tooltips. Adding tooltips to the map can display specific data points on hover, enabling the audience to quickly glean detailed information without extra clicks.
- Consider increasing the font size of plot labels and legends for better readability.

## Data Summary

- In the data summary table, change the font style to a bolder weight and consider a good font for numerical data to improve readability.
- Rename the "UNNAMED: 0" column to a more descriptive column name.

## TREND OF POLLUTANT OVER TIME

- In the line chart, the x-axis date does not adjust properly with the selected time period. If the selected time period is wide, the date could be in years; if it is narrow, the date could be in days.

**Comment by meretelutz** [comment]
Feedback has been addressed in other issues, thanks Joey!
