### ISSUE TITLE
Feedback from Jing Wen

### ISSUE THREAD

**Issue by Jing-19** [UBC-MDS/DSCI-532_2024_2_pollution-tracker#92]
Good work on the dashboard! I like the overall layout and the simplest style of your dashboard. It is very thoughtful to have options of different pollutants allowing users to choose the pollutants that they are interested in. With the bar chart, map, line chart, and summary, I am able to have a comprehensive understanding changes of in pollutants over time and geographical distributions. 

Here are some feedbacks based on my experience using your dashboard.
- select regions under the worldwide comparison, it doesn't seems like it controls any graphs below (map or bar chart) so I was a bit confused about its usage. I suggest either highlighting the region in the map when users choose a specific country or showing the top 15 countries in that region selected in the bar chart. 
- for the line chart, when there is no data available, maybe show a default message to the user that: not enough data points available somewhere to inform the users. 
- Could consider putting the description of the dashboard to the top right under the title, and I believe this will be more clear to the users. 
- for bar chart, maybe remove the y-axis label, there it overlaps with the country names when the country name is too long. 
- 
Overall, good work with the dashboard! Look forward to the final version!

**Comment by meretelutz** [comment]
Bullet point 1 and 2 was addressed in the second milestone.
Bullet point 3 has already been made into an issue and will be addressed.
